document.write("<h1><a href=\"../index.html\"><img src=\"../images/title.png\" width=\"710\" height=\"100\" alt=\"灘校Web新聞\"></a></h1>");
document.write("<ul id=\"nav\">");
document.write("	<li><a href=\"../about.html\">このサイトについて</a></li>");
document.write("	<li><a href=\"../history.html\">更新履歴</a></li>");
document.write("	<li><a href=\"2011.html\" name=\"news\">新聞記事</a>");
document.write("		<ul>");
document.write("			<li><a href=\"2011.html\">2011年度</a>");
document.write("				<ul>");
document.write("                    <li><a href=\"2011.html#England\">英国異文化研修</a>");
document.write("                        <ul>");
document.write("                            <li><a href=\"2011.html#England_Winchester\">ウィンチェスター</a></li>");
document.write("                            <li><a href=\"2011.html#England_Radley\">ラドリー</a></li>");
document.write("                        </ul>");
document.write("                    </li>");
document.write("					<li><a href=\"2011.html#outdoor_activity\">野外活動</a></li>");
document.write("					<li><a href=\"2011.html#school_trip\">修学旅行</a>");
document.write("						<ul>");
document.write("							<li><a href=\"2011.html#school_trip_1\">1日目</a></li>");
document.write("							<li><a href=\"2011.html#school_trip_2\">2日目</a></li>");
document.write("							<li><a href=\"2011.html#school_trip_3\">3日目</a></li>");
document.write("							<li><a href=\"2011.html#school_trip_4\">4日目</a></li>");
document.write("							<li><a href=\"2011.html#school_trip_5\">5日目</a></li>");
document.write("							<li><a href=\"2011.html#school_trip_summary\">総括</a></li>");
document.write("						</ul>");
document.write("					</li>");
document.write("					<li><a href=\"2011.html#school_festival\">文化祭</a></li>");
document.write("				</ul>");
document.write("			</li>");
document.write("			<li><a href=\"2010.html\">2010年度</a>");
document.write("				<ul>");
document.write("					<li><a href=\"2010.html#ekiden\">駅伝</a></li>");
document.write("					<li><a href=\"2010.html#high_graduation\">高校卒業式</a></li>");
document.write("					<li><a href=\"2010.html#art_festival\">学芸祭</a>");
document.write("						<ul>");
document.write("							<li><a href=\"2010.html#art_high\">高校学芸祭</a></li>");
document.write("							<li><a href=\"2010.html#art_middle\">中学学芸祭</a></li>");
document.write("							<li><a href=\"2010.html#art_high_practice\">迫る高校学芸祭！</a></li>");
document.write("						</ul>");
document.write("					</li>");
document.write("					<li><a href=\"2010.html#excursion\">学年別遠足</a></li>");
document.write("					<li><a href=\"2010.html#sports_festival\">体育祭</a>");
document.write("						<ul>");
document.write("							<li><a href=\"2010.html#sports_festival_held\">体育祭開催</a></li>");
document.write("							<li><a href=\"2010.html#game\">競技</a></li>");
document.write("							<li><a href=\"2010.html#curtain\">垂れ幕</a></li>");
document.write("							<li><a href=\"2010.html#gym_suit\">体操服</a></li>");
document.write("						</ul>");
document.write("					</li>");
document.write("					<li><a href=\"2010.html#greeting\">開設のご挨拶</a></li>");
document.write("				</ul>");
document.write("			</li>");
document.write("		</ul>");
document.write("	</li>");
document.write("	<li><a href=\"../column.html\">コラム</a></li>");
document.write("	<li><a name=\"school\">学校紹介</a>");
document.write("		<ul>");
document.write("			<li><a href=\"../establishment.html\">施設紹介</a></li>");
document.write("			<li><a href=\"../club.html\">クラブ・同好会紹介</a>");
document.write("				<ul>");
document.write("					<li><a href=\"../club.html#culture\">文化部</a></li>");
document.write("					<li><a href=\"../club.html#sports\">運動部</a></li>");
document.write("				</ul>");
document.write("			</li>");
document.write("		</ul>");
document.write("	</li>");
document.write("	<li><a href=\"../interview.html\">OBインタビュー</a></li>");
document.write("	<li><a href=\"../other_schools.html\">他校訪問</a></li>");
document.write("	<li><a href=\"../photos.html\">写真資料</a></li>");
document.write("	<li><a href=\"../link.html\">リンク</a></li>");
document.write("</ul>");